$LAB.script(VR.BASE_PATH + '/js/libs/jquery-1.7.1.min.js').wait()
    .script(VR.BASE_PATH + '/js/plugins/jcarousellite-1-0-1.js')
    .script(VR.BASE_PATH + '/js/plugins/wp-polls.js')
    .script(VR.BASE_PATH + '/js/init.js')
    .script('http://assets.pinterest.com/js/pinit.js')